version: '3'

services:
  web:
    image: ghcr.io/argadepp/hospitalims:master
    ports:
      - "8000:8000"
    restart: always  
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Morya@2143
      MYSQL_DATABASE: hms
    ports:
      - "3306:3306"