version: '3'

services:
  web:
    image: ghcr.io/argadepp/hospitalims:master
    ports:
      - "80:80"
    restart: always  
    depends_on:
      - db
    links:
      - db
    volumes:
          - .:/var/www/html/hospital
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Morya@2143
      MYSQL_DATABASE: hms
    ports:
      - "3306:3306"